all: program1 program2 program3

program1: program1.cpp
	g++ -Wall program1.cpp -o program1

program2: program2.cpp
	g++ -Wall program2.cpp -o program2

prgram3: program3.cpp
	g++ -Wall program3.cpp -o program3

clean:
	rm -rf program1.o program1
	rm -rf program2.o program2
	rm -rf program3.o program3
